-- DROP TABLE tbcliente;

-- DROP TABLE tbpagamento;

-- DROP TABLE tbaluno;

-- DROP TABLE tbfiliacao;

CREATE TABLE tbcliente
( ID INT NOT NULL AUTO_INCREMENT,
CPF VARCHAR (11) ,
NOME VARCHAR (100) ,
ENDERECO1 VARCHAR (150) ,
ENDERECO2 VARCHAR (150) ,
BAIRRO VARCHAR (50) ,
CIDADE VARCHAR (50) ,
ESTADO VARCHAR (2) ,
CEP VARCHAR (8) ,
IDADE SMALLINT,
SEXO VARCHAR (1) ,
TELEFONE VARCHAR(12) ,
EMAIL VARCHAR(50) ,
PRIMARY KEY (ID) 
);

CREATE TABLE tbaluno
(  ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (100) ,
ENDERECO1 VARCHAR (150) ,
ENDERECO2 VARCHAR (150) ,
BAIRRO VARCHAR (50) ,
CIDADE VARCHAR (50) ,
ESTADO VARCHAR (2) ,
CEP VARCHAR (8) ,
DATANASCIMENTO DATE ,
IDADE SMALLINT,
SEXO VARCHAR (1) ,
ESCOLA VARCHAR(12) ,
SERIE VARCHAR(50) ,
TURMA VARCHAR(2) ,
PROFESSOR VARCHAR (50) ,
PRIMARY KEY (ID) 
);

CREATE TABLE tbFILIACAO
( IDPAI INT NOT NULL, 
IDFILHO INT NOT NULL, 
PRIMARY KEY (IDPAI, IDFILHO),  
FOREIGN KEY (IDPAI)
REFERENCES tbcliente (ID)
ON UPDATE RESTRICT ON DELETE CASCADE,
FOREIGN KEY (IDFILHO)
REFERENCES tbaluno(Id)
ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE tbPAGAMENTO
(  ID INT NOT NULL AUTO_INCREMENT ,
IDCLIENTE INT NOT NULL ,
DATAINICIO DATE ,
DATAPAGAMENTO DATE,
VALOR FLOAT,
FORMAPAGAMENTO VARCHARACTER (10),
PRIMARY KEY (ID) ,
FOREIGN KEY (IDCLIENTE)
REFERENCES tbcliente(Id)
ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE `tb_comments` (
  `commentsid` int(11) NOT NULL,
  `comments` varchar(200) NOT NULL,
  `userid` int(11) NOT NULL,
  `postsid` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tb_users` (
  `userid` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



SELECT * FROM information_schema. tables where table_schema = 'db_zero_to_hero';

